### ISSUE TITLE
Array plotting should use Neo annotations and utilize ImageSequence object

### ISSUE THREAD

**Issue by mdenker** [INM-6/viziphant#10]
The plotting of array grids (currently: `array_data module`) should utilize information of the Neo object to plot itself, e.g., which electrode is which channel, etc. Currently this is not well solved. This is related to work of @rgutzen in trying to find a nice way to encode this (e.g., using array annotations or even modifications in Neo), but also is related to the imagesequence objects introduced in Neo 0.8.

**Comment by dizcza** [comment]
Obsolete?
We don't have the array_data module.

**Comment by rgutzen** [comment]
I think this is still relevant. For example as plotting routine which takes an imagesequence object  as input, or maybe also an analogsignal + coordinate information. This may need to be then adapted in the future to be coherent with how spatial location is stored in neo objects.

**Comment by dizcza** [comment]
Ok, we'll discuss this on Mon at a grooming session 'cause I'm out of the issue scope currently.

**Comment by Moritz-Alexander-Kern** [comment]
This seems to be outdated? Please reopen and correct me if I'm wrong on this.
