### ISSUE TITLE
Viziphant UE plotting to handle triple correlations (and more)

### ISSUE THREAD

**Issue by mdenker** [INM-6/viziphant#24]
Currently, Viziphant can plot triple correlations, but the labeling is somewhat off, and only the hash [1 1 1] is correctly plotted. For other hashes non-involved neurons should not get a rectangle, e.g., for [1 0 1] no rectangles in cyan or red should be plotted for the middle neuron.

**Comment by Qkley** [comment]
Visual examples of the issue:
Pattern `[1, 0, 1]`

- Panel A labels need to be fixed. Perhaps putting them inside bottom right corner of the raster plot for each spike train.
- Panel C coincident events are marked for the non-involved spike train.
- Panel F unitary events are marked for non-involved spike train.

![UEA_N3_101_pattern_edited](https://user-images.githubusercontent.com/19880994/97307029-75aa8000-185f-11eb-8ff0-21e4edbed97e.png)
