### ISSUE TITLE
Error in plot_isi_histogram for default cutoff value

### ISSUE THREAD

**Issue by JuliaSprenger** [INM-6/viziphant#30]
For viziphant version 0.1.0 the usage of the default parameters for the `plot_isi_histogram` results in 
```
'numpy.float64' object has no attribute 'rescale'
```

Here is a minimal breaking example
```
st = neo.SpikeTrain([1,2,3]*pq.s,t_stop=10*pq.s)
viziphant.statistics.plot_isi_histogram(spiketrains)
```

**Comment by dizcza** [comment]
Thanks, your script actually spot two bugs in ISI plotting ;)

**Comment by dizcza** [comment]
Don't know how to test viziphant other than calling the functions all possible ways to check that no error is triggered.
Currently, I test the doc tests only. But it'll become an issue quickly if viziphant starts growing.
